name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.4.0
  meta: ^1.7.0
  flame_behaviors: ^0.1.1
  flame_signals:
    path: ../../flame_signals_dev

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GemunuLibre
      fonts:
        - asset: assets/fonts/GemunuLibre-Regular.ttf
        - asset: assets/fonts/GemunuLibre-Light.ttf
          weight: 300
        - asset: assets/fonts/GemunuLibre-Bold.ttf
          weight: 700

