name: flame_signals
description: Signal system for Flame Games
version: 0.0.2
homepage: https://github.com/pastordougdev/flame_signals
repository: https://github.com/pastordougdev/flame_signals

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.4.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dartdoc: ^6.0.1
  flame_test: ^1.8.0

flutter: